Feature/search employees
TalaatHarb/cgdm-skills-matrix pull request #3
Opened 2021-09-02 12:36 UTC by asmaaramadan99

## Brief
- Added Login feature , Search employees , Invite users by email to use skill-matrix.

## Changes
 **Login feature** 
  -  Completes Login action with authentication against database.
  -  Handling first time login for new employees with default password.
  -  First time employee resets default password.

**Invite users by email**
  - An interface for adding emails that invitations will be sent to.
     # issue 
               Configuration issue Emails sent are blocked by gmail.

**Search employees** 
 - Search by employee name.
 - Search by skill name. (default all levels). 
 - Search by skill and level.

### Tests
 **Backend Tests**
- test login page 
- test employee search
- test employee set password

**Front-end test** 
- test for search page

2021-09-04 19:19 UTC, hodasamy-cegedim commented on skills-matrix-server/src/main/java/com/cegedim/skillsmatrix/controllers/AddNewUser.java
> +				System.out.println(email);
please remove the System.out.println from the if condition ,in practical we are not allowed to print this lines except on local environments

2021-09-04 19:22 UTC, hodasamy-cegedim commented on skills-matrix-server/src/main/java/com/cegedim/skillsmatrix/controllers/CategoriesController.java
> +	@GetMapping("")
why @GetMapping("") is empty on this class?

2021-09-04 19:23 UTC, hodasamy-cegedim commented on skills-matrix-server/src/main/java/com/cegedim/skillsmatrix/controllers/JobRolesController.java
> +	@GetMapping("")
why @@GetMapping("") is empty

2021-09-04 19:33 UTC, Abdallah-Youssef commented on skills-matrix-server/src/main/java/com/cegedim/skillsmatrix/controllers/AddNewUser.java
> +				System.out.println(email);
Noted. I will fix it right away.

2021-09-04 19:45 UTC, hodasamy-cegedim commented on skills-matrix-server/src/main/java/com/cegedim/skillsmatrix/controllers/AddNewUser.java
> +				System.out.println(email);
Great Thanks

2021-09-04 19:51 UTC, hodasamy-cegedim requested changes
please follow the comments

2021-09-05 14:41 UTC, TalaatHarb approved these changes

2021-09-05 20:01 UTC, Abdallah-Youssef commented
> please follow the comments

Please review the fix in this [commit](https://github.com/TalaatHarb/cgdm-skills-matrix/pull/3/commits/457511d67960dc849c5398e88255bf2e4e91ddd0)

2021-09-06 07:22 UTC, hodasamy-cegedim approved these changes

2021-09-06 08:43 UTC, merged